#ifndef DDT_ERR_H
#define DDT_ERR_H

#include <QString>
class DError
{
public:
    static QString getErrMsg(int code, const QString& strMsg="");
};

enum ErrorType
{
    //![0 无错误]
    DT_NO_ERROR = 0,

    /*通用错误码***************************/
    DT_ERR_PARSE_BASE = 1,
    DT_ERR_INVALID_REQUEST = DT_ERR_PARSE_BASE+0,
    DT_ERR_INVALID_PARAMS = DT_ERR_PARSE_BASE+1,
    DT_ERR_INVALID_METHOD = DT_ERR_PARSE_BASE+2,
    DT_ERR_INVALID_PLUGIN = DT_ERR_PARSE_BASE+3,
    DT_ERR_LIB_FUNC_DT_ERR_LOAD = DT_ERR_PARSE_BASE+4, //库函数加载失败
    DT_ERR_SAVE_FILE = DT_ERR_PARSE_BASE+5,
    DT_ERR_OPEN_FILE = DT_ERR_PARSE_BASE+6,
    DT_ERR_CREATE_FILE = DT_ERR_PARSE_BASE+7,
    DT_ERR_READ_FILE = DT_ERR_PARSE_BASE+8,
    DT_ERR_WRITE_FILE = DT_ERR_PARSE_BASE+9,
    DT_ERR_FILE_NOT_EXIST = DT_ERR_PARSE_BASE+10,
    DT_ERR_NOT_CONNECT = DT_ERR_PARSE_BASE+11,
    DT_ERR_ILLEGAL_OPERATE_OTHER_DEVICE = DT_ERR_PARSE_BASE+12,
    DT_ERR_ALLOCATE_MEMORY =  DT_ERR_PARSE_BASE+13,
    DT_ERR_CONTENT =  DT_ERR_PARSE_BASE+14,
    DT_ERR_PARAM_OUT_RANGE =  DT_ERR_PARSE_BASE+15,

    /*相机相关的错误码**********************/
    DT_ERR_CAMERA_BASE = 3000,
    DT_ERR_CONNECT_CAMERA = DT_ERR_CAMERA_BASE+0,
    DT_ERR_DISCONNECT_CAMERA = DT_ERR_CAMERA_BASE+1,
    DT_ERR_START_VIDEO = DT_ERR_CAMERA_BASE+2,
    DT_ERR_STOP_VIDEO = DT_ERR_CAMERA_BASE+3,
    DT_ERR_TAKE_PHOTO = DT_ERR_CAMERA_BASE+4,
    DT_ERR_CALIBRATE_POS = DT_ERR_CAMERA_BASE+5,
    DT_ERR_CALIBRATE_RESULT = DT_ERR_CAMERA_BASE+6,
    DT_ERR_CALIBRATE_FILE = DT_ERR_CAMERA_BASE+7,
    DT_ERR_USER_COORDINATE = DT_ERR_CAMERA_BASE+8,
    DT_ERR_CALIBRATE_BEGIN = DT_ERR_CAMERA_BASE+9,
    DT_ERR_CALIBRATE_END = DT_ERR_CAMERA_BASE+10,
    DT_ERR_CALIBRATE_SAMPLING = DT_ERR_CAMERA_BASE+11,
    DT_ERR_UPDATE_CALIBRATE_SAMPLING = DT_ERR_CAMERA_BASE+12,
    DT_ERR_SET_CAMERA_IP = DT_ERR_CAMERA_BASE+13,
    DT_ERR_GSET_TYPE_VALUE = DT_ERR_CAMERA_BASE+14,
    DT_ERR_SEARCH_CAMERA = DT_ERR_CAMERA_BASE+15,

    /*IO设备相关错误码*/
    DT_ERR_IODEVICE_BASE = 6000,
    DT_ERR_IODEVICE_OPEN = DT_ERR_IODEVICE_BASE+0,
    DT_ERR_IODEVICE_GETVERSION = DT_ERR_IODEVICE_BASE+1,
    DT_ERR_IODEVICE_GETLIGHTBOARDPARAM = DT_ERR_IODEVICE_BASE+2,
    DT_ERR_IODEVICE_TURNLIGHTON = DT_ERR_IODEVICE_BASE+3,
    DT_ERR_IODEVICE_TURNLIGHTOFF = DT_ERR_IODEVICE_BASE+4,
};

#endif // DDT_ERR_H
